import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { CatalogContent, ContentSection, HomeCatalogData } from '../models/content.model';

// TODO: Replace mock data with HTTP calls to TMDB API
// Base URL: https://api.themoviedb.org/3
// Image base URL: https://image.tmdb.org/t/p/w500
// Authentication: Bearer token via environment variable (never hardcode)

const MOCK_DATA: HomeCatalogData = {
  featuredContent: {
    id: 'content-001',
    title: 'Horizonte Final',
    description:
      'Uma expedição rumo ao desconhecido onde a realidade se fragmenta. Explore as profundezas do espaço e os limites da mente humana nesta jornada épica.',
    type: 'movie',
    genres: ['Ficção Científica', 'Ação', 'Aventura'],
    ageRating: '14+',
    releaseYear: 2026,
    duration: '2h 10min',
    imageUrl: 'assets/images/horizonte-final-card.jpg',
    backgroundUrl: 'assets/images/horizonte-final-bg.jpg',
    badge: 'Novo',
    ranking: 1,
    isNew: true,
    isFavorite: false,
  },
  sections: [
    {
      id: 'best-movies',
      title: 'Melhores filmes',
      layout: 'landscape',
      items: [
        {
          id: 'movie-001',
          title: 'Cidade Sombria',
          description: 'Um suspense futurista em uma cidade controlada por tecnologia e segredos.',
          type: 'movie',
          genres: ['Suspense', 'Cyberpunk'],
          ageRating: '16+',
          releaseYear: 2026,
          duration: '1h 58min',
          imageUrl: 'assets/images/cidade-sombria.jpg',
          backgroundUrl: 'assets/images/cidade-sombria-bg.jpg',
          badge: 'Novo',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'movie-002',
          title: 'Código Vermelho',
          description: 'Uma operação secreta coloca uma equipe de elite contra o tempo.',
          type: 'movie',
          genres: ['Ação', 'Espionagem'],
          ageRating: '16+',
          releaseYear: 2025,
          duration: '2h 04min',
          imageUrl: 'assets/images/codigo-vermelho.jpg',
          backgroundUrl: 'assets/images/codigo-vermelho-bg.jpg',
          badge: 'Top 10',
          ranking: 3,
          isNew: false,
          isFavorite: true,
        },
        {
          id: 'movie-003',
          title: 'Abismo Zero',
          description: 'Uma expedição submarina descobre algo que não deveria existir.',
          type: 'movie',
          genres: ['Terror', 'Aventura'],
          ageRating: '16+',
          releaseYear: 2025,
          duration: '1h 52min',
          imageUrl: 'assets/images/abismo-zero.jpg',
          backgroundUrl: 'assets/images/abismo-zero-bg.jpg',
          badge: null,
          ranking: null,
          isNew: false,
          isFavorite: false,
        },
        {
          id: 'movie-004',
          title: 'Sombra do Passado',
          description: 'Um detetive persegue fantasmas do presente ao passado.',
          type: 'movie',
          genres: ['Drama', 'Mistério'],
          ageRating: '14+',
          releaseYear: 2026,
          duration: '2h 08min',
          imageUrl: 'assets/images/sombra-do-passado.jpg',
          backgroundUrl: 'assets/images/sombra-do-passado-bg.jpg',
          badge: 'Novo',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'movie-005',
          title: 'Velocidade Máxima',
          description: 'Uma corrida ilegal esconde um plano criminoso de bilhões.',
          type: 'movie',
          genres: ['Ação', 'Thriller'],
          ageRating: '14+',
          releaseYear: 2025,
          duration: '1h 44min',
          imageUrl: 'assets/images/velocidade-maxima.jpg',
          backgroundUrl: 'assets/images/velocidade-maxima-bg.jpg',
          badge: null,
          ranking: null,
          isNew: false,
          isFavorite: false,
        },
      ],
    },
    {
      id: 'highlight-series',
      title: 'Séries em destaque',
      layout: 'featured',
      items: [
        {
          id: 'series-001',
          title: 'Distrito 9X',
          description:
            'A resistência começa agora em uma sociedade dividida por tecnologia, poder e sobrevivência.',
          type: 'series',
          genres: ['Ficção Científica', 'Drama'],
          ageRating: '16+',
          releaseYear: 2026,
          duration: '8 episódios',
          imageUrl: 'assets/images/distrito-9x.jpg',
          backgroundUrl: 'assets/images/distrito-9x-bg.jpg',
          badge: 'Nova Temporada',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'series-002',
          title: 'Mente Sombria',
          description: 'Um investigador com habilidades únicas enfrenta casos impossíveis.',
          type: 'series',
          genres: ['Suspense', 'Crime'],
          ageRating: '16+',
          releaseYear: 2025,
          duration: '10 episódios',
          imageUrl: 'assets/images/mente-sombria.jpg',
          backgroundUrl: 'assets/images/mente-sombria-bg.jpg',
          badge: null,
          ranking: null,
          isNew: false,
          isFavorite: true,
        },
        {
          id: 'series-003',
          title: 'A Colônia',
          description: 'Sobreviventes de um colapso global tentam reconstruir a civilização.',
          type: 'series',
          genres: ['Pós-Apocalíptico', 'Drama'],
          ageRating: '16+',
          releaseYear: 2026,
          duration: '6 episódios',
          imageUrl: 'assets/images/a-colonia.jpg',
          backgroundUrl: 'assets/images/a-colonia-bg.jpg',
          badge: 'Novo',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
      ],
    },
    {
      id: 'top-10-brasil',
      title: 'Top 10 no Brasil',
      layout: 'ranking',
      items: [
        {
          id: 'rank-001',
          title: 'Operação Fantasma',
          description: 'Um agente desaparecido retorna para impedir uma conspiração internacional.',
          type: 'movie',
          genres: ['Ação', 'Suspense'],
          ageRating: '16+',
          releaseYear: 2026,
          duration: '2h 01min',
          imageUrl: 'assets/images/operacao-fantasma.jpg',
          backgroundUrl: 'assets/images/operacao-fantasma-bg.jpg',
          badge: 'Top 10',
          ranking: 1,
          isNew: false,
          isFavorite: false,
        },
        {
          id: 'rank-002',
          title: 'A Última Fronteira',
          description: 'Uma jornada espacial que redefine os limites da exploração humana.',
          type: 'movie',
          genres: ['Ficção Científica', 'Aventura'],
          ageRating: '12+',
          releaseYear: 2025,
          duration: '2h 20min',
          imageUrl: 'assets/images/ultima-fronteira.jpg',
          backgroundUrl: 'assets/images/ultima-fronteira-bg.jpg',
          badge: 'Top 10',
          ranking: 2,
          isNew: false,
          isFavorite: false,
        },
        {
          id: 'rank-003',
          title: 'Código Vermelho',
          description: 'Uma operação secreta coloca uma equipe de elite contra o tempo.',
          type: 'movie',
          genres: ['Ação', 'Espionagem'],
          ageRating: '16+',
          releaseYear: 2025,
          duration: '2h 04min',
          imageUrl: 'assets/images/codigo-vermelho.jpg',
          backgroundUrl: 'assets/images/codigo-vermelho-bg.jpg',
          badge: 'Top 10',
          ranking: 3,
          isNew: false,
          isFavorite: true,
        },
        {
          id: 'rank-004',
          title: 'Noite Eterna',
          description: 'Uma cidade mergulha em escuridão perpétua após um fenômeno inexplicável.',
          type: 'series',
          genres: ['Terror', 'Mistério'],
          ageRating: '18+',
          releaseYear: 2026,
          duration: '6 episódios',
          imageUrl: 'assets/images/noite-eterna.jpg',
          backgroundUrl: 'assets/images/noite-eterna-bg.jpg',
          badge: 'Top 10',
          ranking: 4,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'rank-005',
          title: 'Paraíso Perdido',
          description: 'Refugiados descobrem que seu novo lar esconde um segredo perturbador.',
          type: 'series',
          genres: ['Drama', 'Suspense'],
          ageRating: '14+',
          releaseYear: 2025,
          duration: '8 episódios',
          imageUrl: 'assets/images/paraiso-perdido.jpg',
          backgroundUrl: 'assets/images/paraiso-perdido-bg.jpg',
          badge: 'Top 10',
          ranking: 5,
          isNew: false,
          isFavorite: false,
        },
      ],
    },
    {
      id: 'releases',
      title: 'Lançamentos',
      layout: 'poster',
      items: [
        {
          id: 'release-001',
          title: 'Noite de Tempestade',
          description: 'Um farol isolado esconde um mistério durante a pior tempestade do século.',
          type: 'movie',
          genres: ['Drama', 'Mistério'],
          ageRating: '14+',
          releaseYear: 2026,
          duration: '1h 47min',
          imageUrl: 'assets/images/noite-de-tempestade.jpg',
          backgroundUrl: 'assets/images/noite-de-tempestade-bg.jpg',
          badge: 'Novo Filme',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'release-002',
          title: 'Ecos do Silêncio',
          description: 'Uma compositora descobre que suas músicas atraem algo sobrenatural.',
          type: 'movie',
          genres: ['Terror', 'Drama'],
          ageRating: '16+',
          releaseYear: 2026,
          duration: '1h 55min',
          imageUrl: 'assets/images/ecos-do-silencio.jpg',
          backgroundUrl: 'assets/images/ecos-do-silencio-bg.jpg',
          badge: 'Novo Filme',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'release-003',
          title: 'Horizonte Final',
          description: 'Uma expedição rumo ao desconhecido onde a realidade se fragmenta.',
          type: 'movie',
          genres: ['Ficção Científica', 'Ação'],
          ageRating: '14+',
          releaseYear: 2026,
          duration: '2h 10min',
          imageUrl: 'assets/images/horizonte-final-card.jpg',
          backgroundUrl: 'assets/images/horizonte-final-bg.jpg',
          badge: 'Novo Filme',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'release-004',
          title: 'Cidade Sombria',
          description: 'Um suspense futurista em uma cidade controlada por tecnologia.',
          type: 'movie',
          genres: ['Suspense', 'Cyberpunk'],
          ageRating: '16+',
          releaseYear: 2026,
          duration: '1h 58min',
          imageUrl: 'assets/images/cidade-sombria.jpg',
          backgroundUrl: 'assets/images/cidade-sombria-bg.jpg',
          badge: 'Novo Filme',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'release-005',
          title: 'Sombra do Passado',
          description: 'Um detetive persegue fantasmas do presente ao passado.',
          type: 'movie',
          genres: ['Drama', 'Mistério'],
          ageRating: '14+',
          releaseYear: 2026,
          duration: '2h 08min',
          imageUrl: 'assets/images/sombra-do-passado.jpg',
          backgroundUrl: 'assets/images/sombra-do-passado-bg.jpg',
          badge: 'Novo Filme',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
        {
          id: 'release-006',
          title: 'A Colônia',
          description: 'Sobreviventes de um colapso global tentam reconstruir a civilização.',
          type: 'series',
          genres: ['Pós-Apocalíptico', 'Drama'],
          ageRating: '16+',
          releaseYear: 2026,
          duration: '6 episódios',
          imageUrl: 'assets/images/a-colonia.jpg',
          backgroundUrl: 'assets/images/a-colonia-bg.jpg',
          badge: 'Nova Série',
          ranking: null,
          isNew: true,
          isFavorite: false,
        },
      ],
    },
  ],
};

@Injectable({
  providedIn: 'root',
})
export class MovieCatalogService {
  /**
   * Returns the full home catalog data including featured content and sections.
   * TODO: Replace with HttpClient call to TMDB API endpoints:
   *   - Featured: GET /movie/now_playing?language=pt-BR
   *   - Sections: GET /movie/top_rated, /tv/popular, /trending/all/week
   */
  getHomeCatalogData(): Observable<HomeCatalogData> {
    return of(MOCK_DATA);
  }

  /**
   * Returns a specific content section by ID.
   * TODO: Replace with targeted TMDB API calls per section type.
   */
  getSectionById(sectionId: string): Observable<ContentSection | undefined> {
    const section = MOCK_DATA.sections.find((s) => s.id === sectionId);
    return of(section);
  }

  /**
   * Returns content details by ID.
   * TODO: Replace with GET /movie/{id} or /tv/{id} from TMDB API.
   */
  getContentById(contentId: string): Observable<CatalogContent | undefined> {
    const allItems = [
      MOCK_DATA.featuredContent,
      ...MOCK_DATA.sections.flatMap((s) => s.items),
    ];
    return of(allItems.find((item) => item.id === contentId));
  }
}
